import{a as g,i,S as y}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const h of o.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&d(h)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const b="46752777-bc6a55b3d7926eaa971e03cc7",L="https://pixabay.com/api/",v=15;async function f(r,t=1){try{return(await g.get(L,{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:v}})).data}catch{throw new Error("Failed to fetch images")}}const p=r=>{const t=document.querySelector(".gallery");if(r.length===0){i.error({title:"Error",message:"No images match your search query. Please try again!",position:"topRight"});return}const a=r.map(e=>`
        <div class="photo-card">
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${e.likes}</p>
            <p><b>Views</b> ${e.views}</p>
            <p><b>Comments</b> ${e.comments}</p>
            <p><b>Downloads</b> ${e.downloads}</p>
          </div>
        </div>`).join("");t.insertAdjacentHTML("beforeend",a),new y(".gallery a").refresh()},E=()=>{document.querySelector(".gallery").innerHTML=""},m=document.querySelector("#search-form"),s=document.createElement("button"),c=document.querySelector(".loader");let l="",n=1,u=0;s.textContent="Load more";s.classList.add("load-more-button","hidden");document.body.appendChild(s);m.addEventListener("submit",async r=>{if(r.preventDefault(),l=m.elements.query.value.trim(),l===""){i.error({title:"Error",message:"Please enter a search term.",position:"topRight"});return}n=1,E(),s.classList.add("hidden"),c.classList.remove("hidden");try{const t=await f(l,n);u=t.totalHits,t.hits.length>0?(p(t.hits),t.hits.length<u&&s.classList.remove("hidden")):(i.error({title:"Error",message:"No images found. Please try a different query.",position:"topRight"}),s.classList.add("hidden"))}catch(t){console.error(t),i.error({title:"Error",message:"Failed to fetch images.",position:"topRight"})}finally{c.classList.add("hidden")}});s.addEventListener("click",async()=>{n+=1,c.classList.remove("hidden");try{const r=await f(l,n);p(r.hits),(n-1)*15+r.hits.length>=u&&(s.classList.add("hidden"),i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),w()}catch(r){console.error(r),i.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{c.classList.add("hidden")}});function w(){const r=document.querySelector(".gallery"),{height:t}=r.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
